### ISSUE TITLE
As a user I want to be able to create a cluster in my chosen vendor service so I can deploy tasks/pods

### ISSUE THREAD

**Issue by callanmch** [callanmch/UnifiedContainerAPI#1]
**Description:**
Creates a cluster on the vendor service using uCAPI. This will require implementing the abstract method Create_Cluster() in each derived client class.

**Additional Resources:**
- Base class
- Inherited classes for Kubernetes and AWS

**Acceptance Criteria:**
- Overrides abstract method create_cluster from base class for both Kubernetes and AWS classes

**Comment by BlairTwiss** [comment]
Done with changes committed to develop
