### ISSUE TITLE
As a user I want to be able to update a deployment and service in GKE.

### ISSUE THREAD

**Issue by jamesfoote** [callanmch/UnifiedContainerAPI#47]
Description:
Modify/update a task already deployed on a cluster

Additional Resources:
Base class
Inherited classes for GKE and AWS

Acceptance Criteria:
Overrides abstract method update_task from base class for GKE

**Comment by BlairTwiss** [comment]
This may help with this ticket
https://cloud.google.com/container-engine/docs/clusters/upgrade

**Comment by jamesfoote** [comment]
**Issues identified so far:**

- [ ] Identifying location of name and namespace in YAML file
- [ ] Work out how AWS plans implementation so can match signature
- [ ] Major code duplication with run_task (fix?)
- [ ] Needs to be able to accept run_task out put as input (Waiting for testing to see)
