### ISSUE TITLE
As a user I wish to be able to view my credentials in GKE so that I can verify my information.

### ISSUE THREAD

**Issue by jamesfoote** [callanmch/UnifiedContainerAPI#50]
Description:
Allow the user to call a function to access their GKE credentials.

Resources:
None

Acceptance Criteria:
A function get_credentials that allows the user to return the credentials from the already created GKE client.

**Comment by Lawrence-Wooding** [comment]
Feature/#51 covers ticket 50 also. Both tickets can be resolved if this ticket is resolved.
