### ISSUE TITLE
As a user, I want to be able to create an instance within my cluster so that I can run tasks.

### ISSUE THREAD

**Issue by jamesfoote** [callanmch/UnifiedContainerAPI#7]
**Description:**
Creates an instance within a designated cluster on the given service provider. This will require you to implement the Create_Instance() abstract method in each derived client class.

**Additional Resources:**
- Base class
- Inherited classes for GKE and AWS

**Acceptance Criteria:**
- Overrides abstract method create_instance from base class for both GKE and AWS classes

**Comment by callanmch** [comment]
AWS does not allow multiple instance types in single autoscaling group. They also don't allow management of multiple autoscaling groups from a single cluster.
With the intent of creating parity between services the current intent is to use autoscaling groups with a launch configuration that specifies the cluster information to have multiple autoscaling groups working in one cluster.
This should behave in a similar fashion to the node pools from GKE, as you can have multiple node pools in one cluster, but only one instance type in each node pool.
