### ISSUE TITLE
As a user I want to be able to deregister a task so that I can remove them when they are no longer required

### ISSUE THREAD

**Issue by callanmch** [callanmch/UnifiedContainerAPI#8]

**Comment by jamesfoote** [comment]
**Description:**
Removes the task definition from the service. Basically deregister_task in ECS. Difficult to implement in GKE as there is no actual task definition. Discuss how to handle.

**Additional Resources:**
Base class
Inherited classes for GKE and AWS

**Acceptance Criteria:**
Overrides abstract method deregister_task from base class for both GKE and AWS classes
