### ISSUE TITLE
As a user I want to be able to run tasks so that I can run applications

### ISSUE THREAD

**Issue by BlairTwiss** [callanmch/UnifiedContainerAPI#9]
**Description:**
Runs a registered or defined task on a given cluster and instance. This will require you to implement the Run_task() abstract method in each derived client class.

**Additional Resources:**
- Base class
- Inherited classes for Kubernetes and AWS

**Acceptance Criteria:**
- Overrides abstract method run_task from base class for both Kubernetes and AWS classes

**Comment by jamesfoote** [comment]
Changed scope of this issue to now be implementing run_task just for ECS. This is based on discussion about removal of register_task as it's own method.
